name: talkingdata_appanalytics_plugin
description: A Flutter plugin to use the TalkingData App Analytics API.
version: 0.1.0
homepage: https://github.com/TalkingData

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.talkingdata.plugin.appanalytics
        pluginClass: TalkingDataAppAnalyticsPlugin
      ios:
        pluginClass: TalkingDataAppAnalyticsPlugin
